"""Added foreignkey to the one to many relation between battery and coordinates

Revision ID: 001a2b1c4d8e
Revises: b5795231edd4
Create Date: 2024-11-19 18:13:53.232279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001a2b1c4d8e'
down_revision = 'b5795231edd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordinates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('battery_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("battery_id", 'batteries', ['battery_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordinates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('battery_id')

    # ### end Alembic commands ###
