"""Added comments to the coordinates

Revision ID: c83d4781dd7f
Revises: 001a2b1c4d8e
Create Date: 2024-11-26 00:22:07.277469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83d4781dd7f'
down_revision = '001a2b1c4d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordinates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordinates', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
